apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "react-frontend-config-dev"
  namespace: "nblik-dev"
  labels:
    app: "react-frontend-dev"
data:
  API_BASE_URL: "https://api.nblik.com/api/v1/"
  NODE_ENV: "production"
  NODE_MODULES_CACHE: "false"
  NODE_VERBOSE: "false"
  NPM_CONFIG_LOGLEVEL: "error"
  REACT_APP_NAME: "nblik"
  REACT_APP_VERSION: "1.3.8"